### ISSUE TITLE
don't bother with "eot", "svg", or "ttf" font

### ISSUE THREAD

**Issue by Pomax** [flukeout/mozmaker-icon-font#1]
As font technology, the SVG font spec has been abandoned. It turned out to be a terrible idea, and no browsers (except mobile Safari for bizar reasons) support it anymore. `eot` was Microsoft's hack on `ttf` for the web, but WOFF overtook it. These days we don't need a bullet-proof `@font-face` anymore, you just need the single `.woff` font and it'll work properly in everything.

Finally, the `ttf` format is a universal system font, so it actually gets parsed stricter than the `woff` version, even if that's the exact same font without any compression etc. but just wrapped in the `woff` header. If you already have `woff`, also specifying the `ttf` or `otf` is actually a bad idea.

**Comment by flukeout** [comment]
Hey thanks - figured you'd have some good input here. I just used watever Glyphter spit out, so its good to have this guideline. Will update.

**Comment by Pomax** [comment]
if we want to support "real world" users we probably need the `eot` for those Windows XP and older IE users (despite Microsoft no longer supporting those) but the other browser browsers all do WOFF. There's some Android versions that don't, but those same versions also have virtually nonexistent or downright "random behaviour" webfont support (Android <4.3)

**Comment by flukeout** [comment]
Removed all but the ``.woff`` - as you suggested.
