### ISSUE TITLE
Add info icon and update cc icon

### ISSUE THREAD

**Issue by kristinashu** [flukeout/mozmaker-icon-font#15]
Please add a 'i' footer icon for 'info' or 'about' (this will be in the Pulse footer https://github.com/mozilla/network-pulse/issues/178#issuecomment-261323387).

Also think the Creative Commons icon should be filled in like the other footer icons.

Here are the two svgs:
[svgs.zip](https://github.com/flukeout/mozmaker-icon-font/files/598123/svgs.zip)

**Comment by flukeout** [comment]
Thanks @kristinashu - adding now.

**Comment by flukeout** [comment]
Updated & closed - http://flukeout.github.io/mozmaker-icon-font/

**Comment by kristinashu** [comment]
Sweet!
