### ISSUE TITLE
Improve quality & consistency of the icons

### ISSUE THREAD

**Issue by flukeout** [flukeout/mozmaker-icon-font#7]
Got some good feedback from @lovegushwa about the current icons, including...
- Pick a consistent stroke width
- Pick a consistent roundness (or lack thereof) of edges
- Think about when round and sharp corners are appropriate
  - Are rounded corners necessary for small icons?
  - Hard edges are more classic
- Think about icons at their most likely display sizes
  - For many of these, they'll be at 16px, next to type
- Think about hinting at small sizes

Currently, I've got the following system worked out...

![image](https://cloud.githubusercontent.com/assets/25212/14000783/01d253c8-f100-11e5-81e1-9f3e6bdb6eba.png)
- Each icon is designed on a 30x30 grid
- There are two stroke widths available
  - 4px for thick
  - 2px for thin
- Corner radius is 1px
- Mix of hard and rounded corners, as necessary
- Trying to keep angles at 45 degrees when appropriate
- 5px internal padding in round icons for consistent 'weight' of icon

**Changes**
- I think designing at 32x32 with the same stroke widths (4 and 2px) will be good because when the icon is displayed with a height of 16px (the most likely scenario), this will allow the design to scale well because it's shown at 50% of it's original "size"
- Might want to tone down the rounded corners, make them even less round than 1px, it's too subtle at 16px in height anyway, but will be nice just just to have a hint of subtle roundness when the icons are scaled up

cc @sabrinang

**Comment by sabrinang** [comment]
It'll be worth while to try them out inline next to Fira Sans and see how they visually align. 

For the example below, I'm using font-awesome and in some cases the alignment is varied for optical balance that some icons line up on the baseline and some match up to the top of ascenders etc. Also, considering how positive and negative shape icons work together or how they may differ to be visually balanced too.
<img width="1273" alt="screen shot 2016-03-23 at 3 13 28 pm" src="https://cloud.githubusercontent.com/assets/2492510/14002529/d35ee3bc-f109-11e5-9b97-22e9fc8dd2a3.png">

**Comment by lovegushwa** [comment]
@sabrinang digging your feedback above ^

**Comment by flukeout** [comment]
Closing this issue as it is out of scope for now.
